# -*- coding: utf-8 -*-
"""music player

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DY1QFWamaiYTwC3_ii0sFow2tHFeqZHk
"""

import pygame
import tkinter as tk
from tkinter import filedialog

# Initialize Pygame mixer
pygame.mixer.init()

# Function to load and play a music file
def load_music():
    file_path = filedialog.askopenfilename(filetypes=[("Audio Files", "*.mp3 *.wav")])
    if file_path:
        pygame.mixer.music.load(file_path)
        pygame.mixer.music.play()

# Function to pause the music
def pause_music():
    pygame.mixer.music.pause()

# Function to unpause the music
def unpause_music():
    pygame.mixer.music.unpause()

# Function to stop the music
def stop_music():
    pygame.mixer.music.stop()

# Create the main window
root = tk.Tk()
root.title("Music Player")

# Create buttons for the music player
load_button = tk.Button(root, text="Load Music", command=load_music)
load_button.pack()

play_button = tk.Button(root, text="Play", command=load_music)
play_button.pack()

pause_button = tk.Button(root, text="Pause", command=pause_music)
pause_button.pack()

unpause_button = tk.Button(root, text="Unpause", command=unpause_music)
unpause_button.pack()

stop_button = tk.Button(root, text="Stop", command=stop_music)
stop_button.pack()

# Run the main loop
root.mainloop()